/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * Source file: 3GPP TS 29.573 V16.5.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models
type N32fErrorType string

// List of N32fErrorType
const (
	N32fErrorType_INTEGRITY_CHECK_FAILED N32fErrorType = "INTEGRITY_CHECK_FAILED"
	N32fErrorType_INTEGRITY_CHECK_ON_MODIFICATIONS_FAILED N32fErrorType = "INTEGRITY_CHECK_ON_MODIFICATIONS_FAILED"
	N32fErrorType_MODIFICATIONS_INSTRUCTIONS_FAILED N32fErrorType = "MODIFICATIONS_INSTRUCTIONS_FAILED"
	N32fErrorType_DECIPHERING_FAILED N32fErrorType = "DECIPHERING_FAILED"
	N32fErrorType_MESSAGE_RECONSTRUCTION_FAILED N32fErrorType = "MESSAGE_RECONSTRUCTION_FAILED"
	N32fErrorType_CONTEXT_NOT_FOUND N32fErrorType = "CONTEXT_NOT_FOUND"
	N32fErrorType_INTEGRITY_KEY_EXPIRED N32fErrorType = "INTEGRITY_KEY_EXPIRED"
	N32fErrorType_ENCRYPTION_KEY_EXPIRED N32fErrorType = "ENCRYPTION_KEY_EXPIRED"
	N32fErrorType_POLICY_MISMATCH N32fErrorType = "POLICY_MISMATCH"
)