/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * Source file: 3GPP TS 29.573 V16.5.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type IeInfo struct {
	IeLoc IeLocation `json:"ieLoc" yaml:"ieLoc" bson:"ieLoc"`
	IeType IeType `json:"ieType" yaml:"ieType" bson:"ieType"`
	ReqIe string `json:"reqIe,omitempty" yaml:"reqIe" bson:"reqIe"`
	RspIe string `json:"rspIe,omitempty" yaml:"rspIe" bson:"rspIe"`
	IsModifiable bool `json:"isModifiable,omitempty" yaml:"isModifiable" bson:"isModifiable"`
	IsModifiableByIpx map[string]bool `json:"isModifiableByIpx,omitempty" yaml:"isModifiableByIpx" bson:"isModifiableByIpx"`
}
