/*
 * JOSE Protected Message Forwarding API
 *
 * N32-f Message Forwarding Service. © 2021, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved. 
 *
 * Source file: 3GPP TS 29.573 V16.6.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type RequestLine struct {
	Method HttpMethod `json:"method" yaml:"method" bson:"method"`
	Scheme UriScheme `json:"scheme" yaml:"scheme" bson:"scheme"`
	Authority string `json:"authority" yaml:"authority" bson:"authority"`
	Path string `json:"path" yaml:"path" bson:"path"`
	ProtocolVersion string `json:"protocolVersion" yaml:"protocolVersion" bson:"protocolVersion"`
	QueryFragment string `json:"queryFragment,omitempty" yaml:"queryFragment" bson:"queryFragment"`
}
