/*
 * N32 Handshake API
 *
 * N32-c Handshake Service.  © 2020, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).  All rights reserved. 
 *
 * Source file: 3GPP TS 29.573 V16.5.0; 5G System; Public Land Mobile Network (PLMN) Interconnection; Stage 3
 * Url: http://www.3gpp.org/ftp/Specs/archive/29_series/29.573/
 *
 * API version: 1.1.2
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type ProblemDetails struct {
	Type string `json:"type,omitempty" yaml:"type" bson:"type"`
	Title string `json:"title,omitempty" yaml:"title" bson:"title"`
	Status int32 `json:"status,omitempty" yaml:"status" bson:"status"`
	Detail string `json:"detail,omitempty" yaml:"detail" bson:"detail"`
	Instance string `json:"instance,omitempty" yaml:"instance" bson:"instance"`
	Cause string `json:"cause,omitempty" yaml:"cause" bson:"cause"`
	InvalidParams []InvalidParam `json:"invalidParams,omitempty" yaml:"invalidParams" bson:"invalidParams"`
	SupportedFeatures string `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures"`
	TargetScp string `json:"targetScp,omitempty" yaml:"targetScp" bson:"targetScp"`
}
